name: CD - Deploy Backend

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: amigoscode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5332:5432
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Slack message and sha
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"github: https://github.com/ABdou2365/spring-boot-project/commit/${{ github.sha }} - ${{ github.event.head_commit.message }}"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Deployment started slack message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Deployment started :excuseme:"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Building with maven slack message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Building with maven :maven:"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: generate build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Build Package Push with Maven
        run: ./mvnw -ntp -B verify -Ddocker.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build
      - name: pushing image tag to dockerhub slack Message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Image tag:${{steps.build-number.outputs.BUILD_NUMBER}} pushed to 
          https://hub.docker.com/repository/docker/abdomoutawakkil2002996/abde-api :docker:"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update Dockerrun.aws.json api image tag with new build number
        run: |
          echo "Dockerrun.aws.json Before updating the api image tag"
          cat Dockerrun.aws.json
          sed -i -E 's_(abdomoutawakkil2002996/abde-api:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating the api image tag"
          cat Dockerrun.aws.json
      - name: Starting deployment to Elastic Beanstalk slack message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Starting deployment to Elastic Beanstalk :aws:"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Deploy to ELASTIC BEANSTALK
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{secrets.EB_APPLICATION_NAME}}
          environment_name: ${{secrets.EB_ENVIRONMENT_NAME}}
          version_label: ${{steps.build-number.outputs.BUILD_NUMBER}}
          version_description: ${{ github.SHA }}
          region: ${{secrets.EB_REGION}}
          deployment_package: backend/Dockerrun.aws.json
      - name: Commiting to repo slack message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Commiting to repo https://github.com/ABdou2365/spring-boot-project/ :githubloading:"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: commit and push Dockerrun.aws.json
        run : |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{steps.build-number.outputs.BUILD_NUMBER}}"
          git push
      - name: Deployment and commit completed slack message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Deployment and commit completed :check1: ${{ secrets.EB_ENVIRONMENT_URL }} "}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Commiting to repo slack message
        if: always()
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Job status ${{ job.status }}"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}